/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AutomationCampaignSettingsProperty1 } from './automation-campaign-settings-property1';
import { AutomationTrackingOptionsProperty } from './automation-tracking-options-property';
import { AutomationTriggerProperty1 } from './automation-trigger-property1';
import { CampaignReportSummaryProperty } from './campaign-report-summary-property';
import { ListProperty8 } from './list-property8';
import { ResourceLink } from './resource-link';

/**
 * A summary of an individual Automation workflow\'s settings and content.
 * @export
 * @interface AutomationsGetClassicWorkflowInfo200Response
 */
export interface AutomationsGetClassicWorkflowInfo200Response {
    /**
     * A string that identifies the Automation.
     * @type {string}
     * @memberof AutomationsGetClassicWorkflowInfo200Response
     */
    'id'?: string;
    /**
     * The date and time the Automation was created in ISO 8601 format.
     * @type {string}
     * @memberof AutomationsGetClassicWorkflowInfo200Response
     */
    'create_time'?: string;
    /**
     * The date and time the Automation was started in ISO 8601 format.
     * @type {string}
     * @memberof AutomationsGetClassicWorkflowInfo200Response
     */
    'start_time'?: string;
    /**
     * The current status of the Automation.
     * @type {string}
     * @memberof AutomationsGetClassicWorkflowInfo200Response
     */
    'status'?: AutomationsGetClassicWorkflowInfo200ResponseStatusEnum;
    /**
     * The total number of emails sent for the Automation.
     * @type {number}
     * @memberof AutomationsGetClassicWorkflowInfo200Response
     */
    'emails_sent'?: number;
    /**
     * 
     * @type {ListProperty8}
     * @memberof AutomationsGetClassicWorkflowInfo200Response
     */
    'recipients'?: ListProperty8;
    /**
     * 
     * @type {AutomationCampaignSettingsProperty1}
     * @memberof AutomationsGetClassicWorkflowInfo200Response
     */
    'settings'?: AutomationCampaignSettingsProperty1;
    /**
     * 
     * @type {AutomationTrackingOptionsProperty}
     * @memberof AutomationsGetClassicWorkflowInfo200Response
     */
    'tracking'?: AutomationTrackingOptionsProperty;
    /**
     * 
     * @type {AutomationTriggerProperty1}
     * @memberof AutomationsGetClassicWorkflowInfo200Response
     */
    'trigger_settings'?: AutomationTriggerProperty1;
    /**
     * 
     * @type {CampaignReportSummaryProperty}
     * @memberof AutomationsGetClassicWorkflowInfo200Response
     */
    'report_summary'?: CampaignReportSummaryProperty;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof AutomationsGetClassicWorkflowInfo200Response
     */
    '_links'?: Array<ResourceLink>;
}

type AutomationsGetClassicWorkflowInfo200ResponseStatusEnum = 'save' | 'paused' | 'sending'


