/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AbandonedBrowseAutomationProperty6 } from './abandoned-browse-automation-property6';
import { AbandonedCartAutomationProperty6 } from './abandoned-cart-automation-property6';

/**
 * Details for the automations attached to this store.
 * @export
 * @interface AutomationsProperty6
 */
export interface AutomationsProperty6 {
    /**
     * 
     * @type {AbandonedCartAutomationProperty6}
     * @memberof AutomationsProperty6
     */
    'abandoned_cart'?: AbandonedCartAutomationProperty6;
    /**
     * 
     * @type {AbandonedBrowseAutomationProperty6}
     * @memberof AutomationsProperty6
     */
    'abandoned_browse'?: AbandonedBrowseAutomationProperty6;
}

