/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Stats for Campaign A.
 * @export
 * @interface CampaignAProperty
 */
export interface CampaignAProperty {
    /**
     * Bounces for Campaign A.
     * @type {number}
     * @memberof CampaignAProperty
     */
    'bounces'?: number;
    /**
     * Abuse reports for Campaign A.
     * @type {number}
     * @memberof CampaignAProperty
     */
    'abuse_reports'?: number;
    /**
     * Unsubscribes for Campaign A.
     * @type {number}
     * @memberof CampaignAProperty
     */
    'unsubs'?: number;
    /**
     * Recipient Clicks for Campaign A.
     * @type {number}
     * @memberof CampaignAProperty
     */
    'recipient_clicks'?: number;
    /**
     * Forwards for Campaign A.
     * @type {number}
     * @memberof CampaignAProperty
     */
    'forwards'?: number;
    /**
     * Opens from forwards for Campaign A.
     * @type {number}
     * @memberof CampaignAProperty
     */
    'forwards_opens'?: number;
    /**
     * Opens for Campaign A.
     * @type {number}
     * @memberof CampaignAProperty
     */
    'opens'?: number;
    /**
     * The last open for Campaign A.
     * @type {string}
     * @memberof CampaignAProperty
     */
    'last_open'?: string;
    /**
     * Unique opens for Campaign A.
     * @type {number}
     * @memberof CampaignAProperty
     */
    'unique_opens'?: number;
}

