/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * [Default values for campaigns](https://mailchimp.com/help/edit-your-emails-subject-preview-text-from-name-or-from-email-address/) created for this list.
 * @export
 * @interface CampaignDefaultsProperty1
 */
export interface CampaignDefaultsProperty1 {
    /**
     * The default from name for campaigns sent to this list.
     * @type {string}
     * @memberof CampaignDefaultsProperty1
     */
    'from_name'?: string;
    /**
     * The default from email for campaigns sent to this list.
     * @type {string}
     * @memberof CampaignDefaultsProperty1
     */
    'from_email'?: string;
    /**
     * The default subject line for campaigns sent to this list.
     * @type {string}
     * @memberof CampaignDefaultsProperty1
     */
    'subject'?: string;
    /**
     * The default language for this lists\'s forms.
     * @type {string}
     * @memberof CampaignDefaultsProperty1
     */
    'language'?: string;
}

