/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Campaign1 } from './campaign1';
import { ResourceLink } from './resource-link';

/**
 * An array of campaigns.
 * @export
 * @interface CampaignsGetAll200Response
 */
export interface CampaignsGetAll200Response {
    /**
     * An array of campaigns.
     * @type {Array<Campaign1>}
     * @memberof CampaignsGetAll200Response
     */
    'campaigns'?: Array<Campaign1>;
    /**
     * The total number of items matching the query regardless of pagination.
     * @type {number}
     * @memberof CampaignsGetAll200Response
     */
    'total_items'?: number;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof CampaignsGetAll200Response
     */
    '_links'?: Array<ResourceLink>;
}

