/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CapsuleCRMTrackingProperty } from './capsule-crmtracking-property';
import { SalesforceCRMTrackingProperty } from './salesforce-crmtracking-property';

/**
 * The tracking options for a campaign.
 * @export
 * @interface CampaignTrackingOptionsProperty
 */
export interface CampaignTrackingOptionsProperty {
    /**
     * Whether to [track opens](https://mailchimp.com/help/about-open-tracking/). Defaults to `true`. Cannot be set to false for variate campaigns.
     * @type {boolean}
     * @memberof CampaignTrackingOptionsProperty
     */
    'opens'?: boolean;
    /**
     * Whether to [track clicks](https://mailchimp.com/help/enable-and-view-click-tracking/) in the HTML version of the campaign. Defaults to `true`. Cannot be set to false for variate campaigns.
     * @type {boolean}
     * @memberof CampaignTrackingOptionsProperty
     */
    'html_clicks'?: boolean;
    /**
     * Whether to [track clicks](https://mailchimp.com/help/enable-and-view-click-tracking/) in the plain-text version of the campaign. Defaults to `true`. Cannot be set to false for variate campaigns.
     * @type {boolean}
     * @memberof CampaignTrackingOptionsProperty
     */
    'text_clicks'?: boolean;
    /**
     * Deprecated
     * @type {boolean}
     * @memberof CampaignTrackingOptionsProperty
     */
    'goal_tracking'?: boolean;
    /**
     * Whether to enable e-commerce tracking.
     * @type {boolean}
     * @memberof CampaignTrackingOptionsProperty
     */
    'ecomm360'?: boolean;
    /**
     * The custom slug for [Google Analytics](https://mailchimp.com/help/integrate-google-analytics-with-mailchimp/) tracking (max of 50 bytes).
     * @type {string}
     * @memberof CampaignTrackingOptionsProperty
     */
    'google_analytics'?: string;
    /**
     * The custom slug for [ClickTale](https://mailchimp.com/help/additional-tracking-options-for-campaigns/) tracking (max of 50 bytes).
     * @type {string}
     * @memberof CampaignTrackingOptionsProperty
     */
    'clicktale'?: string;
    /**
     * 
     * @type {SalesforceCRMTrackingProperty}
     * @memberof CampaignTrackingOptionsProperty
     */
    'salesforce'?: SalesforceCRMTrackingProperty;
    /**
     * 
     * @type {CapsuleCRMTrackingProperty}
     * @memberof CampaignTrackingOptionsProperty
     */
    'capsule'?: CapsuleCRMTrackingProperty;
}

