/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Updates on campaigns in the process of sending.
 * @export
 * @interface CampaignDeliveryStatusProperty
 */
export interface CampaignDeliveryStatusProperty {
    /**
     * Whether Campaign Delivery Status is enabled for this account and campaign.
     * @type {boolean}
     * @memberof CampaignDeliveryStatusProperty
     */
    'enabled'?: boolean;
    /**
     * Whether a campaign send can be canceled.
     * @type {boolean}
     * @memberof CampaignDeliveryStatusProperty
     */
    'can_cancel'?: boolean;
    /**
     * The current state of a campaign delivery.
     * @type {string}
     * @memberof CampaignDeliveryStatusProperty
     */
    'status'?: CampaignDeliveryStatusPropertyStatusEnum;
    /**
     * The total number of emails confirmed sent for this campaign so far.
     * @type {number}
     * @memberof CampaignDeliveryStatusProperty
     */
    'emails_sent'?: number;
    /**
     * The total number of emails canceled for this campaign.
     * @type {number}
     * @memberof CampaignDeliveryStatusProperty
     */
    'emails_canceled'?: number;
}

type CampaignDeliveryStatusPropertyStatusEnum = 'delivering' | 'delivered' | 'canceling' | 'canceled'


