/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Activity feed item that represents a generic event.
 * @export
 * @interface ContactActivityEvent
 */
export interface ContactActivityEvent {
    /**
     * The type of event activity.
     * @type {string}
     * @memberof ContactActivityEvent
     */
    'activity_type'?: ContactActivityEventActivityTypeEnum;
    /**
     * The created at timestamp in ISO8601.
     * @type {string}
     * @memberof ContactActivityEvent
     */
    'created_at_timestamp'?: string;
    /**
     * The name of the event.
     * @type {string}
     * @memberof ContactActivityEvent
     */
    'event_name'?: string;
    /**
     * An arbitrary datastore containing properties for the given event.
     * @type {Array<string>}
     * @memberof ContactActivityEvent
     */
    'event_properties'?: Array<string>;
}

type ContactActivityEventActivityTypeEnum = 'event'


