/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by interaction with a campaign via Conversations.
 * @export
 * @interface ConversationSegment22
 */
export interface ConversationSegment22 {
    /**
     * 
     * @type {string}
     * @memberof ConversationSegment22
     */
    'condition_type'?: ConversationSegment22ConditionTypeEnum;
    /**
     * Segment by interaction with a campaign via Conversations.
     * @type {string}
     * @memberof ConversationSegment22
     */
    'field': ConversationSegment22FieldEnum;
    /**
     * The status of a member\'s interaction with a conversation. One of the following: has replied or has not replied.
     * @type {string}
     * @memberof ConversationSegment22
     */
    'op': ConversationSegment22OpEnum;
    /**
     * The web id value for a specific campaign or \'any\' to account for subscribers who have/have not interacted with any campaigns.
     * @type {string}
     * @memberof ConversationSegment22
     */
    'value': string;
}

type ConversationSegment22ConditionTypeEnum = 'Conversation'
type ConversationSegment22FieldEnum = 'conversation'
type ConversationSegment22OpEnum = 'member' | 'notmember'


