/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An individual segment condition
 * @export
 * @interface DropdownRadioMergeFieldSegment31
 */
export interface DropdownRadioMergeFieldSegment31 {
    /**
     * 
     * @type {string}
     * @memberof DropdownRadioMergeFieldSegment31
     */
    'condition_type'?: DropdownRadioMergeFieldSegment31ConditionTypeEnum;
    /**
     * A merge field to segment.
     * @type {string}
     * @memberof DropdownRadioMergeFieldSegment31
     */
    'field': string;
    /**
     * Whether the member\'s merge information is/is not a value or is/is not blank.
     * @type {string}
     * @memberof DropdownRadioMergeFieldSegment31
     */
    'op': DropdownRadioMergeFieldSegment31OpEnum;
    /**
     * The value to segment a text merge field with.
     * @type {string}
     * @memberof DropdownRadioMergeFieldSegment31
     */
    'value'?: string;
}

type DropdownRadioMergeFieldSegment31ConditionTypeEnum = 'SelectMerge'
type DropdownRadioMergeFieldSegment31OpEnum = 'is' | 'not' | 'blank' | 'blank_not' | 'notcontain' | 'contains'


