/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * E-Commerce stats for a campaign.
 * @export
 * @interface ECommerceReportProperty6
 */
export interface ECommerceReportProperty6 {
    /**
     * The total orders for a campaign.
     * @type {number}
     * @memberof ECommerceReportProperty6
     */
    'total_orders'?: number;
    /**
     * The total spent for a campaign. Calculated as the sum of all order totals with no deductions.
     * @type {number}
     * @memberof ECommerceReportProperty6
     */
    'total_spent'?: number;
    /**
     * The total revenue for a campaign. Calculated as the sum of all order totals minus shipping and tax totals.
     * @type {number}
     * @memberof ECommerceReportProperty6
     */
    'total_revenue'?: number;
    /**
     * 
     * @type {string}
     * @memberof ECommerceReportProperty6
     */
    'currency_code'?: string;
}

