/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by purchases from a specific store.
 * @export
 * @interface EcommercePurchasedStoreSegment41
 */
export interface EcommercePurchasedStoreSegment41 {
    /**
     * 
     * @type {string}
     * @memberof EcommercePurchasedStoreSegment41
     */
    'condition_type'?: EcommercePurchasedStoreSegment41ConditionTypeEnum;
    /**
     * Segment by purchases from a specific store.
     * @type {string}
     * @memberof EcommercePurchasedStoreSegment41
     */
    'field'?: EcommercePurchasedStoreSegment41FieldEnum;
    /**
     * Members who have or have not purchased from a specific store.
     * @type {string}
     * @memberof EcommercePurchasedStoreSegment41
     */
    'op'?: EcommercePurchasedStoreSegment41OpEnum;
    /**
     * The store id to segment against.
     * @type {string}
     * @memberof EcommercePurchasedStoreSegment41
     */
    'value'?: string;
}

type EcommercePurchasedStoreSegment41ConditionTypeEnum = 'EcommStore'
type EcommercePurchasedStoreSegment41FieldEnum = 'ecomm_store'
type EcommercePurchasedStoreSegment41OpEnum = 'is' | 'not'


