/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressProperty13 } from './address-property13';
import { AutomationsProperty2 } from './automations-property2';
import { ConnectedSiteProperty2 } from './connected-site-property2';
import { ResourceLink } from './resource-link';

/**
 * An individual store in an account.
 * @export
 * @interface EcommerceAddStoreToMailchimpAccountResponse
 */
export interface EcommerceAddStoreToMailchimpAccountResponse {
    /**
     * The unique identifier for the store.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'id'?: string;
    /**
     * The unique identifier for the list that\'s associated with the store. The `list_id` for a specific store can\'t change.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'list_id'?: string;
    /**
     * The name of the store.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'name'?: string;
    /**
     * The e-commerce platform of the store.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'platform'?: string;
    /**
     * The store domain.  The store domain must be unique within a user account.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'domain'?: string;
    /**
     * Whether to disable automations because the store is currently [syncing](https://mailchimp.com/developer/marketing/docs/e-commerce/#pausing-store-automations).
     * @type {boolean}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'is_syncing'?: boolean;
    /**
     * The email address for the store.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'email_address'?: string;
    /**
     * The three-letter ISO 4217 code for the currency that the store accepts.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'currency_code'?: string;
    /**
     * The currency format for the store. For example: `$`, `£`, etc.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'money_format'?: string;
    /**
     * The primary locale for the store. For example: `en`, `de`, etc.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'primary_locale'?: string;
    /**
     * The timezone for the store.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'timezone'?: string;
    /**
     * The store phone number.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'phone'?: string;
    /**
     * 
     * @type {AddressProperty13}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'address'?: AddressProperty13;
    /**
     * 
     * @type {ConnectedSiteProperty2}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'connected_site'?: ConnectedSiteProperty2;
    /**
     * 
     * @type {AutomationsProperty2}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'automations'?: AutomationsProperty2;
    /**
     * The status of the list connected to the store, namely if it\'s deleted or disabled.
     * @type {boolean}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'list_is_active'?: boolean;
    /**
     * The date and time the store was created in ISO 8601 format.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'created_at'?: string;
    /**
     * The date and time the store was last updated in ISO 8601 format.
     * @type {string}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    'updated_at'?: string;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof EcommerceAddStoreToMailchimpAccountResponse
     */
    '_links'?: Array<ResourceLink>;
}

