/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by purchases from a specific store.
 * @export
 * @interface EcommercePurchasedStoreSegment5
 */
export interface EcommercePurchasedStoreSegment5 {
    /**
     * 
     * @type {string}
     * @memberof EcommercePurchasedStoreSegment5
     */
    'condition_type'?: EcommercePurchasedStoreSegment5ConditionTypeEnum;
    /**
     * Segment by purchases from a specific store.
     * @type {string}
     * @memberof EcommercePurchasedStoreSegment5
     */
    'field'?: EcommercePurchasedStoreSegment5FieldEnum;
    /**
     * Members who have or have not purchased from a specific store.
     * @type {string}
     * @memberof EcommercePurchasedStoreSegment5
     */
    'op'?: EcommercePurchasedStoreSegment5OpEnum;
    /**
     * The store id to segment against.
     * @type {string}
     * @memberof EcommercePurchasedStoreSegment5
     */
    'value'?: string;
}

type EcommercePurchasedStoreSegment5ConditionTypeEnum = 'EcommStore'
type EcommercePurchasedStoreSegment5FieldEnum = 'ecomm_store'
type EcommercePurchasedStoreSegment5OpEnum = 'is' | 'not'


