/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ECommerceCartLineItem2 } from './ecommerce-cart-line-item2';
import { ECommerceCustomerProperty11 } from './ecommerce-customer-property11';
import { ResourceLink } from './resource-link';

/**
 * Information about a specific cart.
 * @export
 * @interface EcommerceGetCartInfo200Response
 */
export interface EcommerceGetCartInfo200Response {
    /**
     * A unique identifier for the cart.
     * @type {string}
     * @memberof EcommerceGetCartInfo200Response
     */
    'id'?: string;
    /**
     * 
     * @type {ECommerceCustomerProperty11}
     * @memberof EcommerceGetCartInfo200Response
     */
    'customer'?: ECommerceCustomerProperty11;
    /**
     * A string that uniquely identifies the campaign associated with a cart.
     * @type {string}
     * @memberof EcommerceGetCartInfo200Response
     */
    'campaign_id'?: string;
    /**
     * The URL for the cart. This parameter is required for [Abandoned Cart](https://mailchimp.com/help/create-an-abandoned-cart-email/) automations.
     * @type {string}
     * @memberof EcommerceGetCartInfo200Response
     */
    'checkout_url'?: string;
    /**
     * The three-letter ISO 4217 code for the currency that the cart uses.
     * @type {string}
     * @memberof EcommerceGetCartInfo200Response
     */
    'currency_code'?: string;
    /**
     * The order total for the cart.
     * @type {number}
     * @memberof EcommerceGetCartInfo200Response
     */
    'order_total'?: number;
    /**
     * The total tax for the cart.
     * @type {number}
     * @memberof EcommerceGetCartInfo200Response
     */
    'tax_total'?: number;
    /**
     * An array of the cart\'s line items.
     * @type {Array<ECommerceCartLineItem2>}
     * @memberof EcommerceGetCartInfo200Response
     */
    'lines'?: Array<ECommerceCartLineItem2>;
    /**
     * The date and time the cart was created in ISO 8601 format.
     * @type {string}
     * @memberof EcommerceGetCartInfo200Response
     */
    'created_at'?: string;
    /**
     * The date and time the cart was last updated in ISO 8601 format.
     * @type {string}
     * @memberof EcommerceGetCartInfo200Response
     */
    'updated_at'?: string;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof EcommerceGetCartInfo200Response
     */
    '_links'?: Array<ResourceLink>;
}

