/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ECommerceCartLineItem1 } from './ecommerce-cart-line-item1';
import { ECommerceCustomerProperty1 } from './ecommerce-customer-property1';

/**
 * Information about a specific cart.
 * @export
 * @interface EcommerceUpdateCartByIdRequest
 */
export interface EcommerceUpdateCartByIdRequest {
    /**
     * 
     * @type {ECommerceCustomerProperty1}
     * @memberof EcommerceUpdateCartByIdRequest
     */
    'customer'?: ECommerceCustomerProperty1;
    /**
     * A string that uniquely identifies the campaign associated with a cart.
     * @type {string}
     * @memberof EcommerceUpdateCartByIdRequest
     */
    'campaign_id'?: string;
    /**
     * The URL for the cart. This parameter is required for [Abandoned Cart](https://mailchimp.com/help/create-an-abandoned-cart-email/) automations.
     * @type {string}
     * @memberof EcommerceUpdateCartByIdRequest
     */
    'checkout_url'?: string;
    /**
     * The three-letter ISO 4217 code for the currency that the cart uses.
     * @type {string}
     * @memberof EcommerceUpdateCartByIdRequest
     */
    'currency_code'?: string;
    /**
     * The order total for the cart.
     * @type {number}
     * @memberof EcommerceUpdateCartByIdRequest
     */
    'order_total'?: number;
    /**
     * The total tax for the cart.
     * @type {number}
     * @memberof EcommerceUpdateCartByIdRequest
     */
    'tax_total'?: number;
    /**
     * An array of the cart\'s line items.
     * @type {Array<ECommerceCartLineItem1>}
     * @memberof EcommerceUpdateCartByIdRequest
     */
    'lines'?: Array<ECommerceCartLineItem1>;
}

