/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by purchases from a specific store.
 * @export
 * @interface EcommercePurchasedStoreSegment32
 */
export interface EcommercePurchasedStoreSegment32 {
    /**
     * 
     * @type {string}
     * @memberof EcommercePurchasedStoreSegment32
     */
    'condition_type'?: EcommercePurchasedStoreSegment32ConditionTypeEnum;
    /**
     * Segment by purchases from a specific store.
     * @type {string}
     * @memberof EcommercePurchasedStoreSegment32
     */
    'field'?: EcommercePurchasedStoreSegment32FieldEnum;
    /**
     * Members who have or have not purchased from a specific store.
     * @type {string}
     * @memberof EcommercePurchasedStoreSegment32
     */
    'op'?: EcommercePurchasedStoreSegment32OpEnum;
    /**
     * The store id to segment against.
     * @type {string}
     * @memberof EcommercePurchasedStoreSegment32
     */
    'value'?: string;
}

type EcommercePurchasedStoreSegment32ConditionTypeEnum = 'EcommStore'
type EcommercePurchasedStoreSegment32FieldEnum = 'ecomm_store'
type EcommercePurchasedStoreSegment32OpEnum = 'is' | 'not'


