/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ECommerceCartLineItem2 } from './ecommerce-cart-line-item2';
import { ResourceLink } from './resource-link';

/**
 * A collection of a cart\'s line items.
 * @export
 * @interface EcommerceListCartLines200Response
 */
export interface EcommerceListCartLines200Response {
    /**
     * The store id.
     * @type {string}
     * @memberof EcommerceListCartLines200Response
     */
    'store_id'?: string;
    /**
     * The cart id.
     * @type {string}
     * @memberof EcommerceListCartLines200Response
     */
    'cart_id'?: string;
    /**
     * An array of objects, each representing a cart\'s line item.
     * @type {Array<ECommerceCartLineItem2>}
     * @memberof EcommerceListCartLines200Response
     */
    'lines'?: Array<ECommerceCartLineItem2>;
    /**
     * The total number of items matching the query regardless of pagination.
     * @type {number}
     * @memberof EcommerceListCartLines200Response
     */
    'total_items'?: number;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof EcommerceListCartLines200Response
     */
    '_links'?: Array<ResourceLink>;
}

