/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The email client.
 * @export
 * @interface EmailClient
 */
export interface EmailClient {
    /**
     * The name of the email client.
     * @type {string}
     * @memberof EmailClient
     */
    'client'?: string;
    /**
     * The number of subscribed members who used this email client.
     * @type {number}
     * @memberof EmailClient
     */
    'members'?: number;
}

