/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FacebookAdsGetInfoResponseAllOf2AudienceEmailSource } from './facebook-ads-get-info-response-all-of2-audience-email-source';
import { FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecs } from './facebook-ads-get-info-response-all-of2-audience-targeting-specs';

/**
 * Audience settings
 * @export
 * @interface FacebookAdsGetInfoResponseAllOf2Audience
 */
export interface FacebookAdsGetInfoResponseAllOf2Audience {
    /**
     * Type of the audience
     * @type {string}
     * @memberof FacebookAdsGetInfoResponseAllOf2Audience
     */
    'type'?: FacebookAdsGetInfoResponseAllOf2AudienceTypeEnum;
    /**
     * List or Facebook based audience
     * @type {string}
     * @memberof FacebookAdsGetInfoResponseAllOf2Audience
     */
    'source_type'?: FacebookAdsGetInfoResponseAllOf2AudienceSourceTypeEnum;
    /**
     * 
     * @type {FacebookAdsGetInfoResponseAllOf2AudienceEmailSource}
     * @memberof FacebookAdsGetInfoResponseAllOf2Audience
     */
    'email_source'?: FacebookAdsGetInfoResponseAllOf2AudienceEmailSource;
    /**
     * To include list contacts as part of audience
     * @type {boolean}
     * @memberof FacebookAdsGetInfoResponseAllOf2Audience
     */
    'include_source_in_target'?: boolean;
    /**
     * To find similar audience in given country
     * @type {string}
     * @memberof FacebookAdsGetInfoResponseAllOf2Audience
     */
    'lookalike_country_code'?: string;
    /**
     * 
     * @type {FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecs}
     * @memberof FacebookAdsGetInfoResponseAllOf2Audience
     */
    'targeting_specs'?: FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecs;
}

type FacebookAdsGetInfoResponseAllOf2AudienceTypeEnum = 'Custom Audience' | 'Lookalike Audience' | 'Interest-based Audience'
type FacebookAdsGetInfoResponseAllOf2AudienceSourceTypeEnum = 'facebook' | 'list'


