/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FacebookAdsGetInfoResponseAllOf1
 */
export interface FacebookAdsGetInfoResponseAllOf1 {
    /**
     * 
     * @type {string}
     * @memberof FacebookAdsGetInfoResponseAllOf1
     */
    'email_source_name'?: string;
    /**
     * The date and time the ad was paused in ISO 8601 format.
     * @type {string}
     * @memberof FacebookAdsGetInfoResponseAllOf1
     */
    'paused_at'?: string;
    /**
     * The date and time the ad was ended in ISO 8601 format.
     * @type {string}
     * @memberof FacebookAdsGetInfoResponseAllOf1
     */
    'end_time'?: string;
    /**
     * If the ad has a problem and needs attention.
     * @type {boolean}
     * @memberof FacebookAdsGetInfoResponseAllOf1
     */
    'needs_attention'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FacebookAdsGetInfoResponseAllOf1
     */
    'was_canceled_by_facebook'?: boolean;
}

