/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FacebookAdsListAds200ResponseFacebookAdsInner } from './facebook-ads-list-ads200-response-facebook-ads-inner';
import { ResourceLink } from './resource-link';

/**
 * Contains an array of facebook ads.
 * @export
 * @interface FacebookAdsListAds200Response
 */
export interface FacebookAdsListAds200Response {
    /**
     * 
     * @type {Array<FacebookAdsListAds200ResponseFacebookAdsInner>}
     * @memberof FacebookAdsListAds200Response
     */
    'facebook_ads'?: Array<FacebookAdsListAds200ResponseFacebookAdsInner>;
    /**
     * The total number of items matching the query regardless of pagination.
     * @type {number}
     * @memberof FacebookAdsListAds200Response
     */
    'total_items'?: number;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof FacebookAdsListAds200Response
     */
    '_links'?: Array<ResourceLink>;
}

