/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FacebookAdsGetInfoResponseAllOf2Audience } from './facebook-ads-get-info-response-all-of2-audience';
import { FacebookAdsGetInfoResponseAllOf2Budget } from './facebook-ads-get-info-response-all-of2-budget';
import { FacebookAdsGetInfoResponseAllOf2Channel } from './facebook-ads-get-info-response-all-of2-channel';
import { FacebookAdsGetInfoResponseAllOf2Content } from './facebook-ads-get-info-response-all-of2-content';
import { FacebookAdsGetInfoResponseAllOf2Feedback } from './facebook-ads-get-info-response-all-of2-feedback';
import { FacebookAdsGetInfoResponseAllOf2Site } from './facebook-ads-get-info-response-all-of2-site';

/**
 * A facebook ad.
 * @export
 * @interface FacebookAdsGetInfoResponseAllOf2
 */
export interface FacebookAdsGetInfoResponseAllOf2 {
    /**
     * Check if this ad is connected to a facebook page
     * @type {boolean}
     * @memberof FacebookAdsGetInfoResponseAllOf2
     */
    'is_connected'?: boolean;
    /**
     * Check if this ad has audience setup
     * @type {boolean}
     * @memberof FacebookAdsGetInfoResponseAllOf2
     */
    'has_audience'?: boolean;
    /**
     * Check if this ad has content
     * @type {boolean}
     * @memberof FacebookAdsGetInfoResponseAllOf2
     */
    'has_content'?: boolean;
    /**
     * 
     * @type {FacebookAdsGetInfoResponseAllOf2Channel}
     * @memberof FacebookAdsGetInfoResponseAllOf2
     */
    'channel'?: FacebookAdsGetInfoResponseAllOf2Channel;
    /**
     * 
     * @type {FacebookAdsGetInfoResponseAllOf2Feedback}
     * @memberof FacebookAdsGetInfoResponseAllOf2
     */
    'feedback'?: FacebookAdsGetInfoResponseAllOf2Feedback;
    /**
     * 
     * @type {FacebookAdsGetInfoResponseAllOf2Site}
     * @memberof FacebookAdsGetInfoResponseAllOf2
     */
    'site'?: FacebookAdsGetInfoResponseAllOf2Site;
    /**
     * 
     * @type {FacebookAdsGetInfoResponseAllOf2Audience}
     * @memberof FacebookAdsGetInfoResponseAllOf2
     */
    'audience'?: FacebookAdsGetInfoResponseAllOf2Audience;
    /**
     * 
     * @type {FacebookAdsGetInfoResponseAllOf2Budget}
     * @memberof FacebookAdsGetInfoResponseAllOf2
     */
    'budget'?: FacebookAdsGetInfoResponseAllOf2Budget;
    /**
     * 
     * @type {FacebookAdsGetInfoResponseAllOf2Content}
     * @memberof FacebookAdsGetInfoResponseAllOf2
     */
    'content'?: FacebookAdsGetInfoResponseAllOf2Content;
}

