/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FacebookAdsGetInfoResponseAllOf2ContentAttachments } from './facebook-ads-get-info-response-all-of2-content-attachments';

/**
 * 
 * @export
 * @interface FacebookAdsGetInfoResponseAllOf2Content
 */
export interface FacebookAdsGetInfoResponseAllOf2Content {
    /**
     * 
     * @type {string}
     * @memberof FacebookAdsGetInfoResponseAllOf2Content
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof FacebookAdsGetInfoResponseAllOf2Content
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof FacebookAdsGetInfoResponseAllOf2Content
     */
    'link_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof FacebookAdsGetInfoResponseAllOf2Content
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof FacebookAdsGetInfoResponseAllOf2Content
     */
    'image_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof FacebookAdsGetInfoResponseAllOf2Content
     */
    'call_to_action'?: string;
    /**
     * 
     * @type {Array<FacebookAdsGetInfoResponseAllOf2ContentAttachments>}
     * @memberof FacebookAdsGetInfoResponseAllOf2Content
     */
    'attachments'?: Array<FacebookAdsGetInfoResponseAllOf2ContentAttachments>;
}

