/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An individual file listed in the File Manager.
 * @export
 * @interface FileManagerUploadFileRequest
 */
export interface FileManagerUploadFileRequest {
    /**
     * The id of the folder.
     * @type {number}
     * @memberof FileManagerUploadFileRequest
     */
    'folder_id'?: number;
    /**
     * The name of the file.
     * @type {string}
     * @memberof FileManagerUploadFileRequest
     */
    'name': string;
    /**
     * The base64-encoded contents of the file.
     * @type {string}
     * @memberof FileManagerUploadFileRequest
     */
    'file_data': string;
}

