/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by a specific geographic region.
 * @export
 * @interface GeolocationSegment42
 */
export interface GeolocationSegment42 {
    /**
     * 
     * @type {string}
     * @memberof GeolocationSegment42
     */
    'condition_type'?: GeolocationSegment42ConditionTypeEnum;
    /**
     * Segmenting subscribers who are within a specific location.
     * @type {string}
     * @memberof GeolocationSegment42
     */
    'field': GeolocationSegment42FieldEnum;
    /**
     * Segment members who are within a specific geographic region.
     * @type {string}
     * @memberof GeolocationSegment42
     */
    'op': GeolocationSegment42OpEnum;
    /**
     * The radius of the target location.
     * @type {number}
     * @memberof GeolocationSegment42
     */
    'value': number;
    /**
     * The address of the target location.
     * @type {string}
     * @memberof GeolocationSegment42
     */
    'addr': string;
    /**
     * The latitude of the target location.
     * @type {string}
     * @memberof GeolocationSegment42
     */
    'lat': string;
    /**
     * The longitude of the target location.
     * @type {string}
     * @memberof GeolocationSegment42
     */
    'lng': string;
}

type GeolocationSegment42ConditionTypeEnum = 'IPGeoIn'
type GeolocationSegment42FieldEnum = 'ipgeo'
type GeolocationSegment42OpEnum = 'ipgeoin' | 'ipgeonotin'


