/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by Goal activity.
 * @export
 * @interface GoalActivitySegment29
 */
export interface GoalActivitySegment29 {
    /**
     * 
     * @type {string}
     * @memberof GoalActivitySegment29
     */
    'condition_type'?: GoalActivitySegment29ConditionTypeEnum;
    /**
     * Segment by Goal activity.
     * @type {string}
     * @memberof GoalActivitySegment29
     */
    'field': GoalActivitySegment29FieldEnum;
    /**
     * Whether the website URL is/not exactly, contains/doesn\'t contain, starts with/ends with a string.
     * @type {string}
     * @memberof GoalActivitySegment29
     */
    'op': GoalActivitySegment29OpEnum;
    /**
     * The URL to check Goal activity against.
     * @type {string}
     * @memberof GoalActivitySegment29
     */
    'value': string;
}

type GoalActivitySegment29ConditionTypeEnum = 'GoalActivity'
type GoalActivitySegment29FieldEnum = 'goal'
type GoalActivitySegment29OpEnum = 'is' | 'goal_not' | 'contains' | 'goal_notcontain' | 'starts' | 'ends'


