/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by Goal activity.
 * @export
 * @interface GoalActivitySegment5
 */
export interface GoalActivitySegment5 {
    /**
     * 
     * @type {string}
     * @memberof GoalActivitySegment5
     */
    'condition_type'?: GoalActivitySegment5ConditionTypeEnum;
    /**
     * Segment by Goal activity.
     * @type {string}
     * @memberof GoalActivitySegment5
     */
    'field': GoalActivitySegment5FieldEnum;
    /**
     * Whether the website URL is/not exactly, contains/doesn\'t contain, starts with/ends with a string.
     * @type {string}
     * @memberof GoalActivitySegment5
     */
    'op': GoalActivitySegment5OpEnum;
    /**
     * The URL to check Goal activity against.
     * @type {string}
     * @memberof GoalActivitySegment5
     */
    'value': string;
}

type GoalActivitySegment5ConditionTypeEnum = 'GoalActivity'
type GoalActivitySegment5FieldEnum = 'goal'
type GoalActivitySegment5OpEnum = 'is' | 'goal_not' | 'contains' | 'goal_notcontain' | 'starts' | 'ends'


