/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MemberActivity } from './member-activity';
import { ResourceLink } from './resource-link';

/**
 * The last 50 member events for a list.
 * @export
 * @interface ListsViewRecentActivityEvents200Response
 */
export interface ListsViewRecentActivityEvents200Response {
    /**
     * An array of objects, each representing a member event.
     * @type {Array<MemberActivity>}
     * @memberof ListsViewRecentActivityEvents200Response
     */
    'activity'?: Array<MemberActivity>;
    /**
     * The MD5 hash of the lowercase version of the list member\'s email address.
     * @type {string}
     * @memberof ListsViewRecentActivityEvents200Response
     */
    'email_id'?: string;
    /**
     * As Mailchimp evolves beyond email, you may eventually have contacts without email addresses. While the `email_id` is the MD5 hash of their email address, this `contact_id` is agnostic of contact’s inclusion of an email address.
     * @type {string}
     * @memberof ListsViewRecentActivityEvents200Response
     */
    'contact_id'?: string;
    /**
     * The list id.
     * @type {string}
     * @memberof ListsViewRecentActivityEvents200Response
     */
    'list_id'?: string;
    /**
     * The total number of items matching the query regardless of pagination.
     * @type {number}
     * @memberof ListsViewRecentActivityEvents200Response
     */
    'total_items'?: number;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof ListsViewRecentActivityEvents200Response
     */
    '_links'?: Array<ResourceLink>;
}

