/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EventsProperty8 } from './events-property8';
import { ResourceLink } from './resource-link';
import { SourcesProperty8 } from './sources-property8';

/**
 * Webhook configured for the given list.
 * @export
 * @interface ListsUpdateWebhookSettings200Response
 */
export interface ListsUpdateWebhookSettings200Response {
    /**
     * An string that uniquely identifies this webhook.
     * @type {string}
     * @memberof ListsUpdateWebhookSettings200Response
     */
    'id'?: string;
    /**
     * A valid URL for the Webhook.
     * @type {string}
     * @memberof ListsUpdateWebhookSettings200Response
     */
    'url'?: string;
    /**
     * 
     * @type {EventsProperty8}
     * @memberof ListsUpdateWebhookSettings200Response
     */
    'events'?: EventsProperty8;
    /**
     * 
     * @type {SourcesProperty8}
     * @memberof ListsUpdateWebhookSettings200Response
     */
    'sources'?: SourcesProperty8;
    /**
     * The unique id for the list.
     * @type {string}
     * @memberof ListsUpdateWebhookSettings200Response
     */
    'list_id'?: string;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof ListsUpdateWebhookSettings200Response
     */
    '_links'?: Array<ResourceLink>;
}

