/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ResourceLink } from './resource-link';

/**
 * Assign subscribers to interests to group them together. Interests are referred to as \'group names\' in the Mailchimp application.
 * @export
 * @interface ListsUpdateInterestCategoryInterestResponse
 */
export interface ListsUpdateInterestCategoryInterestResponse {
    /**
     * The id for the interest category.
     * @type {string}
     * @memberof ListsUpdateInterestCategoryInterestResponse
     */
    'category_id'?: string;
    /**
     * The ID for the list that this interest belongs to.
     * @type {string}
     * @memberof ListsUpdateInterestCategoryInterestResponse
     */
    'list_id'?: string;
    /**
     * The ID for the interest.
     * @type {string}
     * @memberof ListsUpdateInterestCategoryInterestResponse
     */
    'id'?: string;
    /**
     * The name of the interest. This can be shown publicly on a subscription form.
     * @type {string}
     * @memberof ListsUpdateInterestCategoryInterestResponse
     */
    'name'?: string;
    /**
     * The number of subscribers associated with this interest.
     * @type {string}
     * @memberof ListsUpdateInterestCategoryInterestResponse
     */
    'subscriber_count'?: string;
    /**
     * The display order for interests.
     * @type {number}
     * @memberof ListsUpdateInterestCategoryInterestResponse
     */
    'display_order'?: number;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof ListsUpdateInterestCategoryInterestResponse
     */
    '_links'?: Array<ResourceLink>;
}

