/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CollectionAuthorizationProperty } from './collection-authorization-property';
import { ResourceLink } from './resource-link';
import { SubscriberList1 } from './subscriber-list1';

/**
 * A collection of subscriber lists for this account. Lists contain subscribers who have opted-in to receive correspondence from you or your organization.
 * @export
 * @interface ListsGetAllInfo200Response
 */
export interface ListsGetAllInfo200Response {
    /**
     * An array of objects, each representing a list.
     * @type {Array<SubscriberList1>}
     * @memberof ListsGetAllInfo200Response
     */
    'lists': Array<SubscriberList1>;
    /**
     * The total number of items matching the query regardless of pagination.
     * @type {number}
     * @memberof ListsGetAllInfo200Response
     */
    'total_items'?: number;
    /**
     * 
     * @type {CollectionAuthorizationProperty}
     * @memberof ListsGetAllInfo200Response
     */
    'constraints'?: CollectionAuthorizationProperty;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof ListsGetAllInfo200Response
     */
    '_links'?: Array<ResourceLink>;
}

