/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Member activity events.
 * @export
 * @interface MemberActivity
 */
export interface MemberActivity {
    /**
     * If set, the campaign\'s title.
     * @type {string}
     * @memberof MemberActivity
     */
    'title'?: string;
    /**
     * The type of action recorded for the subscriber.
     * @type {string}
     * @memberof MemberActivity
     */
    'action'?: string;
    /**
     * The date and time recorded for the action.
     * @type {string}
     * @memberof MemberActivity
     */
    'timestamp'?: string;
    /**
     * For clicks, the URL the subscriber clicked on.
     * @type {string}
     * @memberof MemberActivity
     */
    'url'?: string;
    /**
     * The type of campaign that was sent.
     * @type {string}
     * @memberof MemberActivity
     */
    'type'?: string;
    /**
     * The web-based ID for the campaign.
     * @type {string}
     * @memberof MemberActivity
     */
    'campaign_id'?: string;
    /**
     * The ID of the parent campaign.
     * @type {string}
     * @memberof MemberActivity
     */
    'parent_campaign'?: string;
}

