/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An object describing the open activity for the campaign.
 * @export
 * @interface OpensProperty
 */
export interface OpensProperty {
    /**
     * The total number of opens for a campaign.
     * @type {number}
     * @memberof OpensProperty
     */
    'opens_total'?: number;
    /**
     * The total number of unique opens.
     * @type {number}
     * @memberof OpensProperty
     */
    'unique_opens'?: number;
    /**
     * The number of unique opens divided by the total number of successful deliveries.
     * @type {number}
     * @memberof OpensProperty
     */
    'open_rate'?: number;
    /**
     * The date and time of the last recorded open in ISO 8601 format.
     * @type {string}
     * @memberof OpensProperty
     */
    'last_open'?: string;
}

