/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by predicted age.
 * @export
 * @interface PredictedAgeSegment3
 */
export interface PredictedAgeSegment3 {
    /**
     * 
     * @type {string}
     * @memberof PredictedAgeSegment3
     */
    'condition_type'?: PredictedAgeSegment3ConditionTypeEnum;
    /**
     * Segment by predicted age.
     * @type {string}
     * @memberof PredictedAgeSegment3
     */
    'field': PredictedAgeSegment3FieldEnum;
    /**
     * Members who are/not the exact criteria listed.
     * @type {string}
     * @memberof PredictedAgeSegment3
     */
    'op': PredictedAgeSegment3OpEnum;
    /**
     * The predicted age to segment.
     * @type {string}
     * @memberof PredictedAgeSegment3
     */
    'value': PredictedAgeSegment3ValueEnum;
}

type PredictedAgeSegment3ConditionTypeEnum = 'PredictedAge'
type PredictedAgeSegment3FieldEnum = 'predicted_age_range'
type PredictedAgeSegment3OpEnum = 'is'
type PredictedAgeSegment3ValueEnum = '18-24' | '25-34' | '35-44' | '45-54' | '55-64' | '65+'


