/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by predicted gender.
 * @export
 * @interface PredictedGenderSegment20
 */
export interface PredictedGenderSegment20 {
    /**
     * 
     * @type {string}
     * @memberof PredictedGenderSegment20
     */
    'condition_type'?: PredictedGenderSegment20ConditionTypeEnum;
    /**
     * Segment by predicted gender.
     * @type {string}
     * @memberof PredictedGenderSegment20
     */
    'field': PredictedGenderSegment20FieldEnum;
    /**
     * Members who are/not the exact criteria listed.
     * @type {string}
     * @memberof PredictedGenderSegment20
     */
    'op': PredictedGenderSegment20OpEnum;
    /**
     * The predicted gender to segment.
     * @type {string}
     * @memberof PredictedGenderSegment20
     */
    'value': PredictedGenderSegment20ValueEnum;
}

type PredictedGenderSegment20ConditionTypeEnum = 'PredictedGender'
type PredictedGenderSegment20FieldEnum = 'predicted_gender'
type PredictedGenderSegment20OpEnum = 'is' | 'not'
type PredictedGenderSegment20ValueEnum = 'male' | 'female'


