/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by predicted gender.
 * @export
 * @interface PredictedGenderSegment23
 */
export interface PredictedGenderSegment23 {
    /**
     * 
     * @type {string}
     * @memberof PredictedGenderSegment23
     */
    'condition_type'?: PredictedGenderSegment23ConditionTypeEnum;
    /**
     * Segment by predicted gender.
     * @type {string}
     * @memberof PredictedGenderSegment23
     */
    'field': PredictedGenderSegment23FieldEnum;
    /**
     * Members who are/not the exact criteria listed.
     * @type {string}
     * @memberof PredictedGenderSegment23
     */
    'op': PredictedGenderSegment23OpEnum;
    /**
     * The predicted gender to segment.
     * @type {string}
     * @memberof PredictedGenderSegment23
     */
    'value': PredictedGenderSegment23ValueEnum;
}

type PredictedGenderSegment23ConditionTypeEnum = 'PredictedGender'
type PredictedGenderSegment23FieldEnum = 'predicted_gender'
type PredictedGenderSegment23OpEnum = 'is' | 'not'
type PredictedGenderSegment23ValueEnum = 'male' | 'female'


