/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CampaignReport2 } from './campaign-report2';
import { ResourceLink } from './resource-link';

/**
 * A list of reports containing child campaigns for a specific campaign.
 * @export
 * @interface ReportsListChildCampaignReportsResponse
 */
export interface ReportsListChildCampaignReportsResponse {
    /**
     * An array of objects, each representing a report resource.
     * @type {Array<CampaignReport2>}
     * @memberof ReportsListChildCampaignReportsResponse
     */
    'reports'?: Array<CampaignReport2>;
    /**
     * Unique identifier of the parent campaign
     * @type {string}
     * @memberof ReportsListChildCampaignReportsResponse
     */
    'campaign_id'?: string;
    /**
     * The total number of items matching the query regardless of pagination.
     * @type {number}
     * @memberof ReportsListChildCampaignReportsResponse
     */
    'total_items'?: number;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof ReportsListChildCampaignReportsResponse
     */
    '_links'?: Array<ResourceLink>;
}

