/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmailDomain } from './email-domain';
import { ResourceLink } from './resource-link';

/**
 * Statistics for the top-performing email domains in a campaign.
 * @export
 * @interface ReportsListDomainPerformanceStats200Response
 */
export interface ReportsListDomainPerformanceStats200Response {
    /**
     * The top 5 email domains based on total delivered emails.
     * @type {Array<EmailDomain>}
     * @memberof ReportsListDomainPerformanceStats200Response
     */
    'domains'?: Array<EmailDomain>;
    /**
     * The total number of emails sent for the campaign.
     * @type {number}
     * @memberof ReportsListDomainPerformanceStats200Response
     */
    'total_sent'?: number;
    /**
     * The unique id for the campaign.
     * @type {string}
     * @memberof ReportsListDomainPerformanceStats200Response
     */
    'campaign_id'?: string;
    /**
     * The total number of items matching the query regardless of pagination.
     * @type {number}
     * @memberof ReportsListDomainPerformanceStats200Response
     */
    'total_items'?: number;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof ReportsListDomainPerformanceStats200Response
     */
    '_links'?: Array<ResourceLink>;
}

