/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContactCountsProperty } from './contact-counts-property';
import { MergeFieldProperty } from './merge-field-property';
import { OptionsPropertyInner } from './options-property-inner';

/**
 * The details of a survey question\'s report.
 * @export
 * @interface ReportingSurveyQuestionReport200Response
 */
export interface ReportingSurveyQuestionReport200Response {
    /**
     * The ID of the survey question.
     * @type {string}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'id'?: string;
    /**
     * The unique ID of the survey.
     * @type {string}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'survey_id'?: string;
    /**
     * The query of the survey question.
     * @type {string}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'query'?: string;
    /**
     * The response type of the survey question.
     * @type {string}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'type'?: ReportingSurveyQuestionReport200ResponseTypeEnum;
    /**
     * The total number of responses to this question.
     * @type {number}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'total_responses'?: number;
    /**
     * Whether this survey question is required to answer.
     * @type {boolean}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'is_required'?: boolean;
    /**
     * Whether this survey question has an \'other\' option.
     * @type {boolean}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'has_other'?: boolean;
    /**
     * Label used for the \'other\' option of this survey question.
     * @type {string}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'other_label'?: string;
    /**
     * The average rating for this range question.
     * @type {number}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'average_rating'?: number;
    /**
     * Label for the low end of the range.
     * @type {string}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'range_low_label'?: string;
    /**
     * Label for the high end of the range.
     * @type {string}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'range_high_label'?: string;
    /**
     * Placeholder text for this survey question\'s answer box.
     * @type {string}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'placeholder_label'?: string;
    /**
     * Whether the subscribe checkbox is shown for this email question.
     * @type {boolean}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'subscribe_checkbox_enabled'?: boolean;
    /**
     * Label used for the subscribe checkbox for this email question.
     * @type {string}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'subscribe_checkbox_label'?: string;
    /**
     * 
     * @type {MergeFieldProperty}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'merge_field'?: MergeFieldProperty;
    /**
     * The answer choices for this question.
     * @type {Array<OptionsPropertyInner>}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'options'?: Array<OptionsPropertyInner>;
    /**
     * 
     * @type {ContactCountsProperty}
     * @memberof ReportingSurveyQuestionReport200Response
     */
    'contact_counts'?: ContactCountsProperty;
}

type ReportingSurveyQuestionReport200ResponseTypeEnum = 'pickOne' | 'pickMany' | 'range' | 'text' | 'email'


