/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportingListFacebookAdsReportsResponseFacebookAdsInner } from './reporting-list-facebook-ads-reports-response-facebook-ads-inner';
import { ResourceLink } from './resource-link';

/**
 * A collection of Facebook ads.
 * @export
 * @interface ReportingListFacebookAdsReportsResponse
 */
export interface ReportingListFacebookAdsReportsResponse {
    /**
     * 
     * @type {Array<ReportingListFacebookAdsReportsResponseFacebookAdsInner>}
     * @memberof ReportingListFacebookAdsReportsResponse
     */
    'facebook_ads'?: Array<ReportingListFacebookAdsReportsResponseFacebookAdsInner>;
    /**
     * The total number of items matching the query regardless of pagination.
     * @type {number}
     * @memberof ReportingListFacebookAdsReportsResponse
     */
    'total_items'?: number;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof ReportingListFacebookAdsReportsResponse
     */
    '_links'?: Array<ResourceLink>;
}

