/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FacebookAdsGetInfoResponseAllOf2Audience } from './facebook-ads-get-info-response-all-of2-audience';
import { ReportingFacebookAdReportResponseAllOf1AudienceActivity } from './reporting-facebook-ad-report-response-all-of1-audience-activity';
import { ReportingFacebookAdReportResponseAllOf1Budget } from './reporting-facebook-ad-report-response-all-of1-budget';
import { ReportingFacebookAdReportResponseAllOf1Channel } from './reporting-facebook-ad-report-response-all-of1-channel';
import { ReportingFacebookAdReportResponseAllOf1ReportSummary } from './reporting-facebook-ad-report-response-all-of1-report-summary';

/**
 * 
 * @export
 * @interface ReportingFacebookAdReportResponseAllOf1
 */
export interface ReportingFacebookAdReportResponseAllOf1 {
    /**
     * 
     * @type {ReportingFacebookAdReportResponseAllOf1Channel}
     * @memberof ReportingFacebookAdReportResponseAllOf1
     */
    'channel'?: ReportingFacebookAdReportResponseAllOf1Channel;
    /**
     * 
     * @type {FacebookAdsGetInfoResponseAllOf2Audience}
     * @memberof ReportingFacebookAdReportResponseAllOf1
     */
    'audience'?: FacebookAdsGetInfoResponseAllOf2Audience;
    /**
     * 
     * @type {ReportingFacebookAdReportResponseAllOf1Budget}
     * @memberof ReportingFacebookAdReportResponseAllOf1
     */
    'budget'?: ReportingFacebookAdReportResponseAllOf1Budget;
    /**
     * 
     * @type {ReportingFacebookAdReportResponseAllOf1ReportSummary}
     * @memberof ReportingFacebookAdReportResponseAllOf1
     */
    'report_summary'?: ReportingFacebookAdReportResponseAllOf1ReportSummary;
    /**
     * 
     * @type {ReportingFacebookAdReportResponseAllOf1AudienceActivity}
     * @memberof ReportingFacebookAdReportResponseAllOf1
     */
    'audience_activity'?: ReportingFacebookAdReportResponseAllOf1AudienceActivity;
}

