/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MemberActivity1 } from './member-activity1';
import { ResourceLink } from './resource-link';

/**
 * A list of a member\'s opens activity in a specific campaign.
 * @export
 * @interface ReportsOpenSubscriberDetails200Response
 */
export interface ReportsOpenSubscriberDetails200Response {
    /**
     * The unique id for the campaign.
     * @type {string}
     * @memberof ReportsOpenSubscriberDetails200Response
     */
    'campaign_id'?: string;
    /**
     * The unique id for the list.
     * @type {string}
     * @memberof ReportsOpenSubscriberDetails200Response
     */
    'list_id'?: string;
    /**
     * The status of the list used, namely if it\'s deleted or disabled.
     * @type {boolean}
     * @memberof ReportsOpenSubscriberDetails200Response
     */
    'list_is_active'?: boolean;
    /**
     * The status of the member, namely if they are subscribed, unsubscribed, deleted, non-subscribed, transactional, pending, or need reconfirmation.
     * @type {string}
     * @memberof ReportsOpenSubscriberDetails200Response
     */
    'contact_status'?: string;
    /**
     * The MD5 hash of the lowercase version of the list member\'s email address.
     * @type {string}
     * @memberof ReportsOpenSubscriberDetails200Response
     */
    'email_id'?: string;
    /**
     * Email address for a subscriber.
     * @type {string}
     * @memberof ReportsOpenSubscriberDetails200Response
     */
    'email_address'?: string;
    /**
     * A dictionary of merge fields where the keys are the merge tags. See the [Merge Fields documentation](https://mailchimp.com/developer/marketing/docs/merge-fields/#structure) for more about the structure.
     * @type {{ [key: string]: any; }}
     * @memberof ReportsOpenSubscriberDetails200Response
     */
    'merge_fields'?: { [key: string]: any; };
    /**
     * [VIP status](https://mailchimp.com/help/designate-and-send-to-vip-contacts/) for subscriber.
     * @type {boolean}
     * @memberof ReportsOpenSubscriberDetails200Response
     */
    'vip'?: boolean;
    /**
     * The total number of times the this campaign was opened by the list member.
     * @type {number}
     * @memberof ReportsOpenSubscriberDetails200Response
     */
    'opens_count'?: number;
    /**
     * An array of timestamps for each time a list member opened the campaign. If a list member opens an email multiple times, this will return a separate timestamp for each open event.
     * @type {Array<MemberActivity1>}
     * @memberof ReportsOpenSubscriberDetails200Response
     */
    'opens'?: Array<MemberActivity1>;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof ReportsOpenSubscriberDetails200Response
     */
    '_links'?: Array<ResourceLink>;
}

