/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ResourceLink } from './resource-link';

/**
 * A subscriber\'s status for a specific campaign.
 * @export
 * @interface ReportsCampaignRecipientInfo200Response
 */
export interface ReportsCampaignRecipientInfo200Response {
    /**
     * The MD5 hash of the lowercase version of the list member\'s email address.
     * @type {string}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    'email_id'?: string;
    /**
     * Email address for a subscriber.
     * @type {string}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    'email_address'?: string;
    /**
     * A dictionary of merge fields where the keys are the merge tags. See the [Merge Fields documentation](https://mailchimp.com/developer/marketing/docs/merge-fields/#structure) for more about the structure.
     * @type {{ [key: string]: any; }}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    'merge_fields'?: { [key: string]: any; };
    /**
     * [VIP status](https://mailchimp.com/help/designate-and-send-to-vip-contacts/) for subscriber.
     * @type {boolean}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    'vip'?: boolean;
    /**
     * The status of the email delivered to this subscriber. `hard` and `soft` refer to different [bounce types](https://mailchimp.com/help/soft-vs-hard-bounces/).
     * @type {string}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    'status'?: ReportsCampaignRecipientInfo200ResponseStatusEnum;
    /**
     * The number of times a campaign was opened by this member.
     * @type {number}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    'open_count'?: number;
    /**
     * The date and time of the last open for this member in ISO 8601 format.
     * @type {string}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    'last_open'?: string;
    /**
     * For A/B Split Campaigns, the group the member was apart of.
     * @type {string}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    'absplit_group'?: ReportsCampaignRecipientInfo200ResponseAbsplitGroupEnum;
    /**
     * For campaigns sent with timewarp, the time zone group the member is apart of.
     * @type {number}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    'gmt_offset'?: number;
    /**
     * The campaign id.
     * @type {string}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    'campaign_id'?: string;
    /**
     * The unique list id.
     * @type {string}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    'list_id'?: string;
    /**
     * The status of the list used, namely if it\'s deleted or disabled.
     * @type {boolean}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    'list_is_active'?: boolean;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof ReportsCampaignRecipientInfo200Response
     */
    '_links'?: Array<ResourceLink>;
}

type ReportsCampaignRecipientInfo200ResponseStatusEnum = 'sent' | 'hard' | 'soft'
type ReportsCampaignRecipientInfo200ResponseAbsplitGroupEnum = 'a' | 'b' | 'winner'


