/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ABSplitStatsProperty } from './absplit-stats-property';
import { BouncesProperty } from './bounces-property';
import { CampaignDeliveryStatusProperty } from './campaign-delivery-status-property';
import { ClicksProperty } from './clicks-property';
import { ECommerceReportProperty3 } from './ecommerce-report-property3';
import { FacebookLikesProperty } from './facebook-likes-property';
import { ForwardsProperty } from './forwards-property';
import { IndustryStatsProperty1 } from './industry-stats-property1';
import { ListStatsProperty } from './list-stats-property';
import { OpensProperty } from './opens-property';
import { ResourceLink } from './resource-link';
import { ShareReportProperty } from './share-report-property';
import { TimeseriesPropertyInner } from './timeseries-property-inner';
import { TimewarpStatsPropertyInner } from './timewarp-stats-property-inner';

/**
 * Report details about a sent campaign.
 * @export
 * @interface ReportsSpecificCampaignReportResponse
 */
export interface ReportsSpecificCampaignReportResponse {
    /**
     * A string that uniquely identifies this campaign.
     * @type {string}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'id'?: string;
    /**
     * The title of the campaign.
     * @type {string}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'campaign_title'?: string;
    /**
     * The type of campaign (regular, plain-text, ab_split, rss, automation, variate, or auto).
     * @type {string}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'type'?: string;
    /**
     * The unique list id.
     * @type {string}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'list_id'?: string;
    /**
     * The status of the list used, namely if it\'s deleted or disabled.
     * @type {boolean}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'list_is_active'?: boolean;
    /**
     * The name of the list.
     * @type {string}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'list_name'?: string;
    /**
     * The subject line for the campaign.
     * @type {string}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'subject_line'?: string;
    /**
     * The preview text for the campaign.
     * @type {string}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'preview_text'?: string;
    /**
     * The total number of emails sent for this campaign.
     * @type {number}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'emails_sent'?: number;
    /**
     * The number of abuse reports generated for this campaign.
     * @type {number}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'abuse_reports'?: number;
    /**
     * The total number of unsubscribed members for this campaign.
     * @type {number}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'unsubscribed'?: number;
    /**
     * The date and time a campaign was sent in ISO 8601 format.
     * @type {string}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'send_time'?: string;
    /**
     * For RSS campaigns, the date and time of the last send in ISO 8601 format.
     * @type {string}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'rss_last_send'?: string;
    /**
     * 
     * @type {BouncesProperty}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'bounces'?: BouncesProperty;
    /**
     * 
     * @type {ForwardsProperty}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'forwards'?: ForwardsProperty;
    /**
     * 
     * @type {OpensProperty}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'opens'?: OpensProperty;
    /**
     * 
     * @type {ClicksProperty}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'clicks'?: ClicksProperty;
    /**
     * 
     * @type {FacebookLikesProperty}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'facebook_likes'?: FacebookLikesProperty;
    /**
     * 
     * @type {IndustryStatsProperty1}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'industry_stats'?: IndustryStatsProperty1;
    /**
     * 
     * @type {ListStatsProperty}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'list_stats'?: ListStatsProperty;
    /**
     * 
     * @type {ABSplitStatsProperty}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'ab_split'?: ABSplitStatsProperty;
    /**
     * An hourly breakdown of sends, opens, and clicks if a campaign is sent using timewarp.
     * @type {Array<TimewarpStatsPropertyInner>}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'timewarp'?: Array<TimewarpStatsPropertyInner>;
    /**
     * An hourly breakdown of the performance of the campaign over the first 24 hours.
     * @type {Array<TimeseriesPropertyInner>}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'timeseries'?: Array<TimeseriesPropertyInner>;
    /**
     * 
     * @type {ShareReportProperty}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'share_report'?: ShareReportProperty;
    /**
     * 
     * @type {ECommerceReportProperty3}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'ecommerce'?: ECommerceReportProperty3;
    /**
     * 
     * @type {CampaignDeliveryStatusProperty}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    'delivery_status'?: CampaignDeliveryStatusProperty;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof ReportsSpecificCampaignReportResponse
     */
    '_links'?: Array<ResourceLink>;
}

