/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * This object represents a link from the resource where it is found to another resource or action that may be performed.
 * @export
 * @interface ResourceLink1
 */
export interface ResourceLink1 {
    /**
     * As with an HTML \'rel\' attribute, this describes the type of link.
     * @type {string}
     * @memberof ResourceLink1
     */
    'rel'?: string;
    /**
     * This property contains a fully-qualified URL that can be called to retrieve the linked resource or perform the linked action.
     * @type {string}
     * @memberof ResourceLink1
     */
    'href'?: string;
    /**
     * The HTTP method that should be used when accessing the URL defined in \'href\'.
     * @type {string}
     * @memberof ResourceLink1
     */
    'method'?: ResourceLink1MethodEnum;
    /**
     * For GETs, this is a URL representing the schema that the response should conform to.
     * @type {string}
     * @memberof ResourceLink1
     */
    'targetSchema'?: string;
    /**
     * For HTTP methods that can receive bodies (POST and PUT), this is a URL representing the schema that the body should conform to.
     * @type {string}
     * @memberof ResourceLink1
     */
    'schema'?: string;
}

type ResourceLink1MethodEnum = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | 'HEAD'


