/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SendingScheduleProperty } from './sending-schedule-property';

/**
 * [RSS](https://mailchimp.com/help/share-your-blog-posts-with-mailchimp/) options, specific to an RSS campaign.
 * @export
 * @interface RSSOptionsProperty
 */
export interface RSSOptionsProperty {
    /**
     * The URL for the RSS feed.
     * @type {string}
     * @memberof RSSOptionsProperty
     */
    'feed_url': string;
    /**
     * The frequency of the RSS Campaign.
     * @type {string}
     * @memberof RSSOptionsProperty
     */
    'frequency': RSSOptionsPropertyFrequencyEnum;
    /**
     * 
     * @type {SendingScheduleProperty}
     * @memberof RSSOptionsProperty
     */
    'schedule'?: SendingScheduleProperty;
    /**
     * Whether to add CSS to images in the RSS feed to constrain their width in campaigns.
     * @type {boolean}
     * @memberof RSSOptionsProperty
     */
    'constrain_rss_img'?: boolean;
}

type RSSOptionsPropertyFrequencyEnum = 'daily' | 'weekly' | 'monthly'


