/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExactMatchesProperty1 } from './exact-matches-property1';
import { PartialMatchesProperty1 } from './partial-matches-property1';
import { ResourceLink } from './resource-link';

/**
 * Members found for given search term
 * @export
 * @interface SearchMembersListMembers200Response
 */
export interface SearchMembersListMembers200Response {
    /**
     * 
     * @type {ExactMatchesProperty1}
     * @memberof SearchMembersListMembers200Response
     */
    'exact_matches'?: ExactMatchesProperty1;
    /**
     * 
     * @type {PartialMatchesProperty1}
     * @memberof SearchMembersListMembers200Response
     */
    'full_search'?: PartialMatchesProperty1;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof SearchMembersListMembers200Response
     */
    '_links'?: Array<ResourceLink>;
}

