/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressMergeFieldSegment13 } from './address-merge-field-segment13';
import { AddressZipMergeFieldSegment13 } from './address-zip-merge-field-segment13';
import { AimSegment13 } from './aim-segment13';
import { AutomationSegment13 } from './automation-segment13';
import { BirthdayMergeFieldSegment13 } from './birthday-merge-field-segment13';
import { ConversationSegment13 } from './conversation-segment13';
import { DateMergeFieldSegment13 } from './date-merge-field-segment13';
import { DateSegment13 } from './date-segment13';
import { DropdownRadioMergeFieldSegment13 } from './dropdown-radio-merge-field-segment13';
import { EcommerceCategorySegment13 } from './ecommerce-category-segment13';
import { EcommerceNumberSegment13 } from './ecommerce-number-segment13';
import { EcommercePurchasedSegment13 } from './ecommerce-purchased-segment13';
import { EcommercePurchasedStoreSegment13 } from './ecommerce-purchased-store-segment13';
import { EcommerceSpentSegment13 } from './ecommerce-spent-segment13';
import { EmailClientSegment13 } from './email-client-segment13';
import { EmailSegment13 } from './email-segment13';
import { GeolocationSegment13 } from './geolocation-segment13';
import { GoalActivitySegment13 } from './goal-activity-segment13';
import { GoalTimestampSegment13 } from './goal-timestamp-segment13';
import { InterestsSegment13 } from './interests-segment13';
import { LanguageSegment13 } from './language-segment13';
import { LocationBasedSegment13 } from './location-based-segment13';
import { MemberRatingSegment13 } from './member-rating-segment13';
import { NewSubscribersPrebuiltSegment } from './new-subscribers-prebuilt-segment';
import { PollActivitySegment13 } from './poll-activity-segment13';
import { PredictedAgeSegment13 } from './predicted-age-segment13';
import { PredictedGenderSegment13 } from './predicted-gender-segment13';
import { SignupSourceSegment13 } from './signup-source-segment13';
import { SimilarSubscribersSegmentMemberSegment13 } from './similar-subscribers-segment-member-segment13';
import { SocialProfilesAgeSegment13 } from './social-profiles-age-segment13';
import { SocialProfilesGenderSegment13 } from './social-profiles-gender-segment13';
import { SocialProfilesInfluenceSegment13 } from './social-profiles-influence-segment13';
import { SocialProfilesSocialNetworkFollowSegment13 } from './social-profiles-social-network-follow-segment13';
import { SocialProfilesSocialNetworkSegment13 } from './social-profiles-social-network-segment13';
import { StaticSegmentMemberSegment13 } from './static-segment-member-segment13';
import { SurveyMonkeySegment13 } from './survey-monkey-segment13';
import { TextOrNumberMergeFieldSegment13 } from './text-or-number-merge-field-segment13';
import { USZipCodeSegment13 } from './uszip-code-segment13';
import { UnknownLocationBasedSegment13 } from './unknown-location-based-segment13';
import { VIPSegment13 } from './vipsegment13';
import { ZipCodeLocationBasedSegment13 } from './zip-code-location-based-segment13';

/**
 * @type SegmentTypePropertyInner12
 * @export
 */
export type SegmentTypePropertyInner12 = AddressMergeFieldSegment13 | AddressZipMergeFieldSegment13 | AimSegment13 | AutomationSegment13 | BirthdayMergeFieldSegment13 | ConversationSegment13 | DateMergeFieldSegment13 | DateSegment13 | DropdownRadioMergeFieldSegment13 | EcommerceCategorySegment13 | EcommerceNumberSegment13 | EcommercePurchasedSegment13 | EcommercePurchasedStoreSegment13 | EcommerceSpentSegment13 | EmailClientSegment13 | EmailSegment13 | GeolocationSegment13 | GoalActivitySegment13 | GoalTimestampSegment13 | InterestsSegment13 | LanguageSegment13 | LocationBasedSegment13 | MemberRatingSegment13 | NewSubscribersPrebuiltSegment | PollActivitySegment13 | PredictedAgeSegment13 | PredictedGenderSegment13 | SignupSourceSegment13 | SimilarSubscribersSegmentMemberSegment13 | SocialProfilesAgeSegment13 | SocialProfilesGenderSegment13 | SocialProfilesInfluenceSegment13 | SocialProfilesSocialNetworkFollowSegment13 | SocialProfilesSocialNetworkSegment13 | StaticSegmentMemberSegment13 | SurveyMonkeySegment13 | TextOrNumberMergeFieldSegment13 | USZipCodeSegment13 | UnknownLocationBasedSegment13 | VIPSegment13 | ZipCodeLocationBasedSegment13;


