/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressMergeFieldSegment25 } from './address-merge-field-segment25';
import { AddressZipMergeFieldSegment25 } from './address-zip-merge-field-segment25';
import { AimSegment25 } from './aim-segment25';
import { AutomationSegment25 } from './automation-segment25';
import { BirthdayMergeFieldSegment25 } from './birthday-merge-field-segment25';
import { ConversationSegment25 } from './conversation-segment25';
import { DateMergeFieldSegment25 } from './date-merge-field-segment25';
import { DateSegment25 } from './date-segment25';
import { DropdownRadioMergeFieldSegment25 } from './dropdown-radio-merge-field-segment25';
import { EcommerceCategorySegment25 } from './ecommerce-category-segment25';
import { EcommerceNumberSegment25 } from './ecommerce-number-segment25';
import { EcommercePurchasedSegment25 } from './ecommerce-purchased-segment25';
import { EcommercePurchasedStoreSegment25 } from './ecommerce-purchased-store-segment25';
import { EcommerceSpentSegment25 } from './ecommerce-spent-segment25';
import { EmailClientSegment25 } from './email-client-segment25';
import { EmailSegment25 } from './email-segment25';
import { GeolocationSegment25 } from './geolocation-segment25';
import { GoalActivitySegment25 } from './goal-activity-segment25';
import { GoalTimestampSegment25 } from './goal-timestamp-segment25';
import { InterestsSegment25 } from './interests-segment25';
import { LanguageSegment25 } from './language-segment25';
import { LocationBasedSegment25 } from './location-based-segment25';
import { MemberRatingSegment25 } from './member-rating-segment25';
import { NewSubscribersPrebuiltSegment } from './new-subscribers-prebuilt-segment';
import { PollActivitySegment25 } from './poll-activity-segment25';
import { PredictedAgeSegment25 } from './predicted-age-segment25';
import { PredictedGenderSegment25 } from './predicted-gender-segment25';
import { SignupSourceSegment25 } from './signup-source-segment25';
import { SimilarSubscribersSegmentMemberSegment25 } from './similar-subscribers-segment-member-segment25';
import { SocialProfilesAgeSegment25 } from './social-profiles-age-segment25';
import { SocialProfilesGenderSegment25 } from './social-profiles-gender-segment25';
import { SocialProfilesInfluenceSegment25 } from './social-profiles-influence-segment25';
import { SocialProfilesSocialNetworkFollowSegment25 } from './social-profiles-social-network-follow-segment25';
import { SocialProfilesSocialNetworkSegment25 } from './social-profiles-social-network-segment25';
import { StaticSegmentMemberSegment25 } from './static-segment-member-segment25';
import { SurveyMonkeySegment25 } from './survey-monkey-segment25';
import { TextOrNumberMergeFieldSegment25 } from './text-or-number-merge-field-segment25';
import { USZipCodeSegment25 } from './uszip-code-segment25';
import { UnknownLocationBasedSegment25 } from './unknown-location-based-segment25';
import { VIPSegment25 } from './vipsegment25';
import { ZipCodeLocationBasedSegment25 } from './zip-code-location-based-segment25';

/**
 * @type SegmentTypePropertyInner24
 * @export
 */
export type SegmentTypePropertyInner24 = AddressMergeFieldSegment25 | AddressZipMergeFieldSegment25 | AimSegment25 | AutomationSegment25 | BirthdayMergeFieldSegment25 | ConversationSegment25 | DateMergeFieldSegment25 | DateSegment25 | DropdownRadioMergeFieldSegment25 | EcommerceCategorySegment25 | EcommerceNumberSegment25 | EcommercePurchasedSegment25 | EcommercePurchasedStoreSegment25 | EcommerceSpentSegment25 | EmailClientSegment25 | EmailSegment25 | GeolocationSegment25 | GoalActivitySegment25 | GoalTimestampSegment25 | InterestsSegment25 | LanguageSegment25 | LocationBasedSegment25 | MemberRatingSegment25 | NewSubscribersPrebuiltSegment | PollActivitySegment25 | PredictedAgeSegment25 | PredictedGenderSegment25 | SignupSourceSegment25 | SimilarSubscribersSegmentMemberSegment25 | SocialProfilesAgeSegment25 | SocialProfilesGenderSegment25 | SocialProfilesInfluenceSegment25 | SocialProfilesSocialNetworkFollowSegment25 | SocialProfilesSocialNetworkSegment25 | StaticSegmentMemberSegment25 | SurveyMonkeySegment25 | TextOrNumberMergeFieldSegment25 | USZipCodeSegment25 | UnknownLocationBasedSegment25 | VIPSegment25 | ZipCodeLocationBasedSegment25;


