/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CollectionOfContentForListSignupForms1 } from './collection-of-content-for-list-signup-forms1';
import { CollectionOfElementStyleForListSignupForms1 } from './collection-of-element-style-for-list-signup-forms1';
import { ResourceLink } from './resource-link';
import { SignupFormHeaderOptionsProperty1 } from './signup-form-header-options-property1';

/**
 * List signup form.
 * @export
 * @interface SignupForm
 */
export interface SignupForm {
    /**
     * 
     * @type {SignupFormHeaderOptionsProperty1}
     * @memberof SignupForm
     */
    'header'?: SignupFormHeaderOptionsProperty1;
    /**
     * The signup form body content.
     * @type {Array<CollectionOfContentForListSignupForms1>}
     * @memberof SignupForm
     */
    'contents'?: Array<CollectionOfContentForListSignupForms1>;
    /**
     * An array of objects, each representing an element style for the signup form.
     * @type {Array<CollectionOfElementStyleForListSignupForms1>}
     * @memberof SignupForm
     */
    'styles'?: Array<CollectionOfElementStyleForListSignupForms1>;
    /**
     * Signup form URL.
     * @type {string}
     * @memberof SignupForm
     */
    'signup_form_url'?: string;
    /**
     * The signup form\'s list id.
     * @type {string}
     * @memberof SignupForm
     */
    'list_id'?: string;
    /**
     * A list of link types and descriptions for the API schema documents.
     * @type {Array<ResourceLink>}
     * @memberof SignupForm
     */
    '_links'?: Array<ResourceLink>;
}

