/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by signup source.
 * @export
 * @interface SignupSourceSegment
 */
export interface SignupSourceSegment {
    /**
     * 
     * @type {string}
     * @memberof SignupSourceSegment
     */
    'condition_type': SignupSourceSegmentConditionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SignupSourceSegment
     */
    'field': SignupSourceSegmentFieldEnum;
    /**
     * Whether the member\'s signup source was/was not a particular value.
     * @type {string}
     * @memberof SignupSourceSegment
     */
    'op': SignupSourceSegmentOpEnum;
    /**
     * The signup source.
     * @type {string}
     * @memberof SignupSourceSegment
     */
    'value'?: string;
}

type SignupSourceSegmentConditionTypeEnum = 'SignupSource'
type SignupSourceSegmentFieldEnum = 'source'
type SignupSourceSegmentOpEnum = 'source_is' | 'source_not'


