/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by listed gender in Social Profiles data.
 * @export
 * @interface SocialProfilesGenderSegment30
 */
export interface SocialProfilesGenderSegment30 {
    /**
     * 
     * @type {string}
     * @memberof SocialProfilesGenderSegment30
     */
    'condition_type'?: SocialProfilesGenderSegment30ConditionTypeEnum;
    /**
     * Segment by listed gender in Social Profiles data.
     * @type {string}
     * @memberof SocialProfilesGenderSegment30
     */
    'field': SocialProfilesGenderSegment30FieldEnum;
    /**
     * Members who are/not the exact criteria listed.
     * @type {string}
     * @memberof SocialProfilesGenderSegment30
     */
    'op': SocialProfilesGenderSegment30OpEnum;
    /**
     * The Social Profiles gender to segment.
     * @type {string}
     * @memberof SocialProfilesGenderSegment30
     */
    'value': SocialProfilesGenderSegment30ValueEnum;
}

type SocialProfilesGenderSegment30ConditionTypeEnum = 'SocialGender'
type SocialProfilesGenderSegment30FieldEnum = 'social_gender'
type SocialProfilesGenderSegment30OpEnum = 'is' | 'not'
type SocialProfilesGenderSegment30ValueEnum = 'male' | 'female'


