/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by social network in Social Profiles data.
 * @export
 * @interface SocialProfilesSocialNetworkFollowSegment35
 */
export interface SocialProfilesSocialNetworkFollowSegment35 {
    /**
     * 
     * @type {string}
     * @memberof SocialProfilesSocialNetworkFollowSegment35
     */
    'condition_type'?: SocialProfilesSocialNetworkFollowSegment35ConditionTypeEnum;
    /**
     * Segment by social network in Social Profiles data.
     * @type {string}
     * @memberof SocialProfilesSocialNetworkFollowSegment35
     */
    'field': SocialProfilesSocialNetworkFollowSegment35FieldEnum;
    /**
     * Members who are/not following a linked account on a given social network.
     * @type {string}
     * @memberof SocialProfilesSocialNetworkFollowSegment35
     */
    'op': SocialProfilesSocialNetworkFollowSegment35OpEnum;
    /**
     * The social network to segment against.
     * @type {string}
     * @memberof SocialProfilesSocialNetworkFollowSegment35
     */
    'value': SocialProfilesSocialNetworkFollowSegment35ValueEnum;
}

type SocialProfilesSocialNetworkFollowSegment35ConditionTypeEnum = 'SocialNetworkFollow'
type SocialProfilesSocialNetworkFollowSegment35FieldEnum = 'social_network'
type SocialProfilesSocialNetworkFollowSegment35OpEnum = 'follow' | 'notfollow'
type SocialProfilesSocialNetworkFollowSegment35ValueEnum = 'twitter_follow'


