/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by listed gender in Social Profiles data.
 * @export
 * @interface SocialProfilesGenderSegment37
 */
export interface SocialProfilesGenderSegment37 {
    /**
     * 
     * @type {string}
     * @memberof SocialProfilesGenderSegment37
     */
    'condition_type'?: SocialProfilesGenderSegment37ConditionTypeEnum;
    /**
     * Segment by listed gender in Social Profiles data.
     * @type {string}
     * @memberof SocialProfilesGenderSegment37
     */
    'field': SocialProfilesGenderSegment37FieldEnum;
    /**
     * Members who are/not the exact criteria listed.
     * @type {string}
     * @memberof SocialProfilesGenderSegment37
     */
    'op': SocialProfilesGenderSegment37OpEnum;
    /**
     * The Social Profiles gender to segment.
     * @type {string}
     * @memberof SocialProfilesGenderSegment37
     */
    'value': SocialProfilesGenderSegment37ValueEnum;
}

type SocialProfilesGenderSegment37ConditionTypeEnum = 'SocialGender'
type SocialProfilesGenderSegment37FieldEnum = 'social_gender'
type SocialProfilesGenderSegment37OpEnum = 'is' | 'not'
type SocialProfilesGenderSegment37ValueEnum = 'male' | 'female'


