/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by social network in Social Profiles data.
 * @export
 * @interface SocialProfilesSocialNetworkFollowSegment
 */
export interface SocialProfilesSocialNetworkFollowSegment {
    /**
     * 
     * @type {string}
     * @memberof SocialProfilesSocialNetworkFollowSegment
     */
    'condition_type'?: SocialProfilesSocialNetworkFollowSegmentConditionTypeEnum;
    /**
     * Segment by social network in Social Profiles data.
     * @type {string}
     * @memberof SocialProfilesSocialNetworkFollowSegment
     */
    'field': SocialProfilesSocialNetworkFollowSegmentFieldEnum;
    /**
     * Members who are/not following a linked account on a given social network.
     * @type {string}
     * @memberof SocialProfilesSocialNetworkFollowSegment
     */
    'op': SocialProfilesSocialNetworkFollowSegmentOpEnum;
    /**
     * The social network to segment against.
     * @type {string}
     * @memberof SocialProfilesSocialNetworkFollowSegment
     */
    'value': SocialProfilesSocialNetworkFollowSegmentValueEnum;
}

type SocialProfilesSocialNetworkFollowSegmentConditionTypeEnum = 'SocialNetworkFollow'
type SocialProfilesSocialNetworkFollowSegmentFieldEnum = 'social_network'
type SocialProfilesSocialNetworkFollowSegmentOpEnum = 'follow' | 'notfollow'
type SocialProfilesSocialNetworkFollowSegmentValueEnum = 'twitter_follow'


