/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by listed gender in Social Profiles data.
 * @export
 * @interface SocialProfilesGenderSegment13
 */
export interface SocialProfilesGenderSegment13 {
    /**
     * 
     * @type {string}
     * @memberof SocialProfilesGenderSegment13
     */
    'condition_type'?: SocialProfilesGenderSegment13ConditionTypeEnum;
    /**
     * Segment by listed gender in Social Profiles data.
     * @type {string}
     * @memberof SocialProfilesGenderSegment13
     */
    'field': SocialProfilesGenderSegment13FieldEnum;
    /**
     * Members who are/not the exact criteria listed.
     * @type {string}
     * @memberof SocialProfilesGenderSegment13
     */
    'op': SocialProfilesGenderSegment13OpEnum;
    /**
     * The Social Profiles gender to segment.
     * @type {string}
     * @memberof SocialProfilesGenderSegment13
     */
    'value': SocialProfilesGenderSegment13ValueEnum;
}

type SocialProfilesGenderSegment13ConditionTypeEnum = 'SocialGender'
type SocialProfilesGenderSegment13FieldEnum = 'social_gender'
type SocialProfilesGenderSegment13OpEnum = 'is' | 'not'
type SocialProfilesGenderSegment13ValueEnum = 'male' | 'female'


