/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by listed gender in Social Profiles data.
 * @export
 * @interface SocialProfilesGenderSegment24
 */
export interface SocialProfilesGenderSegment24 {
    /**
     * 
     * @type {string}
     * @memberof SocialProfilesGenderSegment24
     */
    'condition_type'?: SocialProfilesGenderSegment24ConditionTypeEnum;
    /**
     * Segment by listed gender in Social Profiles data.
     * @type {string}
     * @memberof SocialProfilesGenderSegment24
     */
    'field': SocialProfilesGenderSegment24FieldEnum;
    /**
     * Members who are/not the exact criteria listed.
     * @type {string}
     * @memberof SocialProfilesGenderSegment24
     */
    'op': SocialProfilesGenderSegment24OpEnum;
    /**
     * The Social Profiles gender to segment.
     * @type {string}
     * @memberof SocialProfilesGenderSegment24
     */
    'value': SocialProfilesGenderSegment24ValueEnum;
}

type SocialProfilesGenderSegment24ConditionTypeEnum = 'SocialGender'
type SocialProfilesGenderSegment24FieldEnum = 'social_gender'
type SocialProfilesGenderSegment24OpEnum = 'is' | 'not'
type SocialProfilesGenderSegment24ValueEnum = 'male' | 'female'


