/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by listed gender in Social Profiles data.
 * @export
 * @interface SocialProfilesGenderSegment18
 */
export interface SocialProfilesGenderSegment18 {
    /**
     * 
     * @type {string}
     * @memberof SocialProfilesGenderSegment18
     */
    'condition_type'?: SocialProfilesGenderSegment18ConditionTypeEnum;
    /**
     * Segment by listed gender in Social Profiles data.
     * @type {string}
     * @memberof SocialProfilesGenderSegment18
     */
    'field': SocialProfilesGenderSegment18FieldEnum;
    /**
     * Members who are/not the exact criteria listed.
     * @type {string}
     * @memberof SocialProfilesGenderSegment18
     */
    'op': SocialProfilesGenderSegment18OpEnum;
    /**
     * The Social Profiles gender to segment.
     * @type {string}
     * @memberof SocialProfilesGenderSegment18
     */
    'value': SocialProfilesGenderSegment18ValueEnum;
}

type SocialProfilesGenderSegment18ConditionTypeEnum = 'SocialGender'
type SocialProfilesGenderSegment18FieldEnum = 'social_gender'
type SocialProfilesGenderSegment18OpEnum = 'is' | 'not'
type SocialProfilesGenderSegment18ValueEnum = 'male' | 'female'


