/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Stats for the list. Many of these are cached for at least five minutes.
 * @export
 * @interface StatisticsProperty
 */
export interface StatisticsProperty {
    /**
     * The number of active members in the list.
     * @type {number}
     * @memberof StatisticsProperty
     */
    'member_count'?: number;
    /**
     * The number of contacts in the list, including subscribed, unsubscribed, pending, cleaned, deleted, transactional, and those that need to be reconfirmed. Requires include_total_contacts query parameter to be included.
     * @type {number}
     * @memberof StatisticsProperty
     */
    'total_contacts'?: number;
    /**
     * The number of members who have unsubscribed from the list.
     * @type {number}
     * @memberof StatisticsProperty
     */
    'unsubscribe_count'?: number;
    /**
     * The number of members cleaned from the list.
     * @type {number}
     * @memberof StatisticsProperty
     */
    'cleaned_count'?: number;
    /**
     * The number of active members in the list since the last campaign was sent.
     * @type {number}
     * @memberof StatisticsProperty
     */
    'member_count_since_send'?: number;
    /**
     * The number of members who have unsubscribed since the last campaign was sent.
     * @type {number}
     * @memberof StatisticsProperty
     */
    'unsubscribe_count_since_send'?: number;
    /**
     * The number of members cleaned from the list since the last campaign was sent.
     * @type {number}
     * @memberof StatisticsProperty
     */
    'cleaned_count_since_send'?: number;
    /**
     * The number of campaigns in any status that use this list.
     * @type {number}
     * @memberof StatisticsProperty
     */
    'campaign_count'?: number;
    /**
     * The date and time the last campaign was sent to this list in ISO 8601 format. This is updated when a campaign is sent to 10 or more recipients.
     * @type {string}
     * @memberof StatisticsProperty
     */
    'campaign_last_sent'?: string;
    /**
     * The number of merge fields ([audience field](https://mailchimp.com/help/getting-started-with-merge-tags/)) for this list (doesn\'t include EMAIL).
     * @type {number}
     * @memberof StatisticsProperty
     */
    'merge_field_count'?: number;
    /**
     * The average number of subscriptions per month for the list (not returned if we haven\'t calculated it yet).
     * @type {number}
     * @memberof StatisticsProperty
     */
    'avg_sub_rate'?: number;
    /**
     * The average number of unsubscriptions per month for the list (not returned if we haven\'t calculated it yet).
     * @type {number}
     * @memberof StatisticsProperty
     */
    'avg_unsub_rate'?: number;
    /**
     * The target number of subscriptions per month for the list to keep it growing (not returned if we haven\'t calculated it yet).
     * @type {number}
     * @memberof StatisticsProperty
     */
    'target_sub_rate'?: number;
    /**
     * The average open rate (a percentage represented as a number between 0 and 100) per campaign for the list (not returned if we haven\'t calculated it yet).
     * @type {number}
     * @memberof StatisticsProperty
     */
    'open_rate'?: number;
    /**
     * The average click rate (a percentage represented as a number between 0 and 100) per campaign for the list (not returned if we haven\'t calculated it yet).
     * @type {number}
     * @memberof StatisticsProperty
     */
    'click_rate'?: number;
    /**
     * The date and time of the last time someone subscribed to this list in ISO 8601 format.
     * @type {string}
     * @memberof StatisticsProperty
     */
    'last_sub_date'?: string;
    /**
     * The date and time of the last time someone unsubscribed from this list in ISO 8601 format.
     * @type {string}
     * @memberof StatisticsProperty
     */
    'last_unsub_date'?: string;
}

