/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment members whose location information is unknown.
 * @export
 * @interface UnknownLocationBasedSegment2
 */
export interface UnknownLocationBasedSegment2 {
    /**
     * 
     * @type {string}
     * @memberof UnknownLocationBasedSegment2
     */
    'condition_type'?: UnknownLocationBasedSegment2ConditionTypeEnum;
    /**
     * Segmenting subscribers who are within a specific location.
     * @type {string}
     * @memberof UnknownLocationBasedSegment2
     */
    'field': UnknownLocationBasedSegment2FieldEnum;
    /**
     * Segment members for which location information is unknown.
     * @type {string}
     * @memberof UnknownLocationBasedSegment2
     */
    'op': UnknownLocationBasedSegment2OpEnum;
}

type UnknownLocationBasedSegment2ConditionTypeEnum = 'IPGeoUnknown'
type UnknownLocationBasedSegment2FieldEnum = 'ipgeo'
type UnknownLocationBasedSegment2OpEnum = 'ipgeounknown'


