/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment members whose location information is unknown.
 * @export
 * @interface UnknownLocationBasedSegment39
 */
export interface UnknownLocationBasedSegment39 {
    /**
     * 
     * @type {string}
     * @memberof UnknownLocationBasedSegment39
     */
    'condition_type'?: UnknownLocationBasedSegment39ConditionTypeEnum;
    /**
     * Segmenting subscribers who are within a specific location.
     * @type {string}
     * @memberof UnknownLocationBasedSegment39
     */
    'field': UnknownLocationBasedSegment39FieldEnum;
    /**
     * Segment members for which location information is unknown.
     * @type {string}
     * @memberof UnknownLocationBasedSegment39
     */
    'op': UnknownLocationBasedSegment39OpEnum;
}

type UnknownLocationBasedSegment39ConditionTypeEnum = 'IPGeoUnknown'
type UnknownLocationBasedSegment39FieldEnum = 'ipgeo'
type UnknownLocationBasedSegment39OpEnum = 'ipgeounknown'


