/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by a specific US ZIP code.
 * @export
 * @interface USZipCodeSegment21
 */
export interface USZipCodeSegment21 {
    /**
     * 
     * @type {string}
     * @memberof USZipCodeSegment21
     */
    'condition_type'?: USZipCodeSegment21ConditionTypeEnum;
    /**
     * Segmenting subscribers who are within a specific location.
     * @type {string}
     * @memberof USZipCodeSegment21
     */
    'field': USZipCodeSegment21FieldEnum;
    /**
     * Segment members who are within a specific US zip code.
     * @type {string}
     * @memberof USZipCodeSegment21
     */
    'op': USZipCodeSegment21OpEnum;
    /**
     * The radius of the target location.
     * @type {number}
     * @memberof USZipCodeSegment21
     */
    'value': number;
    /**
     * The zip code to segment against.
     * @type {number}
     * @memberof USZipCodeSegment21
     */
    'extra': number;
}

type USZipCodeSegment21ConditionTypeEnum = 'IPGeoInZip'
type USZipCodeSegment21FieldEnum = 'ipgeo'
type USZipCodeSegment21OpEnum = 'ipgeoinzip'


