/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by a specific US ZIP code.
 * @export
 * @interface USZipCodeSegment42
 */
export interface USZipCodeSegment42 {
    /**
     * 
     * @type {string}
     * @memberof USZipCodeSegment42
     */
    'condition_type'?: USZipCodeSegment42ConditionTypeEnum;
    /**
     * Segmenting subscribers who are within a specific location.
     * @type {string}
     * @memberof USZipCodeSegment42
     */
    'field': USZipCodeSegment42FieldEnum;
    /**
     * Segment members who are within a specific US zip code.
     * @type {string}
     * @memberof USZipCodeSegment42
     */
    'op': USZipCodeSegment42OpEnum;
    /**
     * The radius of the target location.
     * @type {number}
     * @memberof USZipCodeSegment42
     */
    'value': number;
    /**
     * The zip code to segment against.
     * @type {number}
     * @memberof USZipCodeSegment42
     */
    'extra': number;
}

type USZipCodeSegment42ConditionTypeEnum = 'IPGeoInZip'
type USZipCodeSegment42FieldEnum = 'ipgeo'
type USZipCodeSegment42OpEnum = 'ipgeoinzip'


