/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ClicksProperty1Inner5 } from './clicks-property1-inner5';
import { UniqueVisitsPropertyInner5 } from './unique-visits-property-inner5';
import { VisitsPropertyInner5 } from './visits-property-inner5';

/**
 * The clicks and visits data from the last five weeks.
 * @export
 * @interface WeeklyClicksAndVisitsDataProperty2
 */
export interface WeeklyClicksAndVisitsDataProperty2 {
    /**
     * The total number of clicks in a week.
     * @type {Array<ClicksProperty1Inner5>}
     * @memberof WeeklyClicksAndVisitsDataProperty2
     */
    'clicks'?: Array<ClicksProperty1Inner5>;
    /**
     * The total number of visits in a week.
     * @type {Array<VisitsPropertyInner5>}
     * @memberof WeeklyClicksAndVisitsDataProperty2
     */
    'visits'?: Array<VisitsPropertyInner5>;
    /**
     * 
     * @type {Array<UniqueVisitsPropertyInner5>}
     * @memberof WeeklyClicksAndVisitsDataProperty2
     */
    'unique_visits'?: Array<UniqueVisitsPropertyInner5>;
}

