/*
Mailchimp Marketing API

Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.

The version of the OpenAPI document: 3.0.55
Contact: apihelp@mailchimp.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Segment by a specific US ZIP code.
 * @export
 * @interface ZipCodeLocationBasedSegment17
 */
export interface ZipCodeLocationBasedSegment17 {
    /**
     * 
     * @type {string}
     * @memberof ZipCodeLocationBasedSegment17
     */
    'condition_type'?: ZipCodeLocationBasedSegment17ConditionTypeEnum;
    /**
     * Segmenting subscribers who are within a specific location.
     * @type {string}
     * @memberof ZipCodeLocationBasedSegment17
     */
    'field': ZipCodeLocationBasedSegment17FieldEnum;
    /**
     * Segment members who are/are not within a specific US zip code.
     * @type {string}
     * @memberof ZipCodeLocationBasedSegment17
     */
    'op': ZipCodeLocationBasedSegment17OpEnum;
    /**
     * The 5-digit zip code.
     * @type {number}
     * @memberof ZipCodeLocationBasedSegment17
     */
    'value': number;
}

type ZipCodeLocationBasedSegment17ConditionTypeEnum = 'IPGeoZip'
type ZipCodeLocationBasedSegment17FieldEnum = 'ipgeo'
type ZipCodeLocationBasedSegment17OpEnum = 'ipgeoiszip' | 'ipgeonotzip'


